site_name: "Juniper Mist Slack bot"
site_description: "Build a Slack bot with Bolt."
site_url: "https://cdot65.github.io/slackbot-juniper-mist/"
repo_name: "cdot65/slackbot-juniper-mist"
repo_url: "https://github.com/cdot65/slackbot-juniper-mist"
edit_uri: "edit/mainline/site/content"
copyright: "Copyright &copy; 2022 cdot65"
docs_dir: "site/content"
site_dir: "docs"
extra_css:
  - "stylesheets/extra.css"
extra:
  alternate:
    - name: "English"
      link: "./en/"
      lang: "en"

nav:
  - Home: "index.md"
  - Documentation:
      - Overview: "docs/overview.md"
      - Slack Bot:
          - Overview: "docs/slackbot/overview.md"
      - Juniper Mist:
          - Overview: "docs/mist/overview.md"

theme:
  name: "material"
  custom_dir: "site/overrides"
  palette:
    primary: "white"
  font: false
  icon:
    logo: "octicons/terminal-16"
  favicon: "assets/images/favicon.png"
  language: "en"
  features:
    - "tabs"
    - "instant"

markdown_extensions:
  - "admonition"
  - "pymdownx.details"
  - "pymdownx.superfences"
  - "pymdownx.tabbed"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - "site/overrides/.icons"

plugins:
  - "search"
  # - redirects:
  #     redirect_maps:
  #       "docs/juniper-vlabs.md": "docs/lab-environment/juniper-vlabs.md"
  #       "docs/locally.md": "docs/lab-environment/local.md"
  # - macros:
  #     include_dir: "site/content/docs/include"
